# Generated by Django 4.2.6 on 2023-11-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_sales_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainlink',
            name='debt_to_the_supplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='задолженность перед поставщиком'),
        ),
    ]
