# Generated by Django 4.2.6 on 2023-11-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_sales_network', '0002_alter_chainlink_debt_to_the_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainlink',
            name='is_factory',
            field=models.BooleanField(default=False, verbose_name='завод'),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='is_individual_entrepreneur',
            field=models.BooleanField(default=False, verbose_name='индивидуальный предприниматель'),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='is_retail_network',
            field=models.BooleanField(default=False, verbose_name='розничная сеть'),
        ),
    ]
